title: Яндекс.Браузер | Скачать Яндекс Браузер
description: - бесплатно на русском языке. Быстрый, безопасный и удобный браузер с защитой от вирусов, встроенным переводчиком и умной строкой
baseurl: "https://loadbrowser.github.io"      # если сайт на username.github.io
url: "https://loadbrowser.github.io"
