title: Проверка
description: цццБесплатно на русском языке. Быстрый, безопасный и удобный браузер с защитой от вирусов, встроенным переводчиком и умной строкой поиска.

baseurl: "" # если сайт на домене вида username.github.io
url: "https://loadbrowser.github.io"
